from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_main_directories_exist():
    expected_dirs = [
        "config",
        "docs",
        "data/staging",
        "data/raw/sample",
        "data/processed",
        "logs",
        "src/db",
        "src/ingestion",
        "src/ingestion/promotion",
        "src/identity",
        "src/staging",
        "src/validation",
        "src/features",
        "src/models",
        "src/prediction",
        "src/simulation",
        "src/evaluation",
        "src/orchestration",
        "src/utils",
        "tests",
        "scripts",
    ]

    for relative_path in expected_dirs:
        assert (ROOT / relative_path).is_dir()


def test_required_files_exist():
    expected_files = [
        ".env.example",
        "docker-compose.yml",
        "README.md",
        "pyproject.toml",
        "requirements.txt",
        "config/app.yaml",
        "config/batches.yaml",
        "config/feature_config.yaml",
        "config/model_config.yaml",
        "config/simulation_config.yaml",
        "config/source_config.yaml",
        "docs/MASTER_DOCUMENT.md",
        "docs/DECISIONS.md",
        "docs/RUNBOOK.md",
        "scripts/setup_dev.sh",
        "scripts/start_db.sh",
        "scripts/stop_db.sh",
        "scripts/reset_db.sh",
        "scripts/check.sh",
        "scripts/run_batch.sh",
        "scripts/init_db.sh",
        "scripts/db_healthcheck.sh",
        "scripts/db_counts.sh",
        "scripts/seed_batches.sh",
        "scripts/smoke_staging.sh",
        "scripts/smoke_importers.sh",
        "scripts/audit_sample_source.sh",
        "scripts/audit_historical_results_source.sh",
        "scripts/promote_historical_results.sh",
        "scripts/promote_fixtures.sh",
        "scripts/smoke_promote_historical_results.sh",
        "scripts/seed_sample_historical_results.sh",
        "scripts/seed_sample_fixtures.sh",
        "src/db/base.py",
        "src/db/connection.py",
        "src/db/models.py",
        "src/db/init_db.py",
        "src/db/drop_db.py",
        "src/db/healthcheck.py",
        "src/db/counts.py",
        "src/db/batch_seed.py",
        "src/db/assign_batch_matches.py",
        "src/identity/normalizers.py",
        "src/identity/matching.py",
        "src/identity/team_identity.py",
        "src/identity/player_identity.py",
        "src/identity/generic_identity.py",
        "src/staging/paths.py",
        "src/staging/jsonl.py",
        "src/staging/metadata.py",
        "src/validation/results.py",
        "src/validation/common_checks.py",
        "src/validation/dataset_validator.py",
        "src/validation/reporting.py",
        "src/ingestion/import_run.py",
        "src/ingestion/importers/base.py",
        "src/ingestion/importers/teams_importer.py",
        "src/ingestion/importers/fixtures_importer.py",
        "src/ingestion/importers/historical_results_importer.py",
        "src/ingestion/importers/elo_importer.py",
        "src/ingestion/importers/fifa_ranking_importer.py",
        "src/ingestion/importers/players_importer.py",
        "src/ingestion/source_audit.py",
        "src/ingestion/source_registry.py",
        "src/ingestion/source_audits/historical_results_audit.py",
        "src/ingestion/promotion/reports.py",
        "src/ingestion/promotion/historical_results_promoter.py",
        "src/ingestion/promotion/fixtures_promoter.py",
        "tests/test_identity_normalizers.py",
        "tests/test_identity_matching.py",
        "tests/test_team_identity.py",
        "tests/test_player_identity.py",
        "tests/test_staging_paths.py",
        "tests/test_staging_jsonl.py",
        "tests/test_validation_common_checks.py",
        "tests/test_dataset_validator.py",
        "tests/test_import_run.py",
        "tests/test_importer_base.py",
        "tests/test_teams_importer.py",
        "tests/test_fixtures_importer.py",
        "tests/test_historical_results_importer.py",
        "tests/test_elo_importer.py",
        "tests/test_fifa_ranking_importer.py",
        "tests/test_players_importer.py",
        "tests/test_source_audit.py",
        "tests/test_source_registry.py",
        "tests/test_historical_results_audit.py",
        "tests/test_promotion_reports.py",
        "tests/test_historical_results_promoter.py",
        "tests/test_db_counts.py",
        "tests/test_seed_script_contract.py",
        "tests/test_fixtures_promoter.py",
        "tests/test_batch_seed.py",
        "tests/test_assign_batch_matches.py",
        "tests/test_seed_fixtures_script_contract.py",
    ]

    for relative_path in expected_files:
        assert (ROOT / relative_path).is_file()
