#!/usr/bin/env bash

set -euo pipefail

source .venv/bin/activate

python - <<'PY'
import json
from pathlib import Path

from src.ingestion.import_run import create_import_run, finalize_import_run
from src.validation.dataset_validator import DatasetValidator

normalized_records = [
    {"row_id": 1, "match_id": "m1", "team": "USA", "metric_value": 3},
    {"row_id": 2, "match_id": "m2", "metric_value": 1},
    {"row_id": 3, "match_id": "m3", "team": "France", "metric_value": -2},
    {"row_id": 4, "match_id": "m1", "team": "USA", "metric_value": 3},
]

run_dir = create_import_run(
    source_name="smoke_source",
    source_type="smoke_test",
    metadata={"notes": "Generated by scripts/smoke_staging.sh"},
)

validator = DatasetValidator(
    required_fields=["match_id", "team", "metric_value"],
    duplicate_key_fields=["match_id", "team"],
)
valid_records, rejected_records, validation_result = validator.validate(
    normalized_records
)
report = finalize_import_run(
    run_dir=run_dir,
    normalized_records=normalized_records,
    valid_records=valid_records,
    rejected_records=rejected_records,
    validation_result=validation_result,
)

expected_files = [
    "normalized.jsonl",
    "valid.jsonl",
    "rejected.jsonl",
    "validation_report.json",
    "review_report.md",
    "metadata.json",
]
missing = [name for name in expected_files if not (run_dir / name).is_file()]
if missing:
    raise SystemExit(f"Missing expected staging files: {missing}")

print(f"run_dir={run_dir}")
print(json.dumps(report, indent=2, sort_keys=True))
PY
